apiVersion: v1
kind: Deployment
metadata:
  namespace: mongo
  annotations:
  creationTimestamp: null
  generation: 1
  labels:
    app: mongodb
  name: mongodb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mongodb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongodb
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: mongodb-creds
        image: mongo:6.0.2
        imagePullPolicy: Always
        name: mongodb
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/db
          name: mongo-data-db
        - mountPath: /data/configdb
          name: mongo-data-db
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mongo-data-db
        persistentVolumeClaim:
          claimName: mongodb-pvc
