apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mongo
  labels:
    app: mongodb
  name: mongodb-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi
