#####
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-client-pod
  namespace: mongo
  labels:
    app: mcheck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcheck
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mcheck
    spec:
      containers:
      - name: mcheck-qualdo
        imagePullPolicy: Always
        image: 666959237374.dkr.ecr.eu-west-1.amazonaws.com/qualdo:q_mongo_client_1

---
---

apiVersion: v1
kind: Service
metadata:
  name: mcheck-service
  namespace: mongo
spec:
  selector:
    app: mcheck
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
