apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-node-2-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 10.9.80.58
    path: "/kubernetes/mongo-node-2"