apiVersion: v1
kind: PersistentVolume
metadata:
  name: ref1-mongo-pv
  namespace: qualdo
  labels:
    usage: ref1-mongo-pv
spec:
  storageClassName: ref1-azurefile-mongo-sc
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: ref1-azure-mongo-secret
    shareName: qualdo-mongo-dev1
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ref1-mongo-pvc
  namespace: qualdo
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ref1-azurefile-mongo-sc
  resources:
    requests:
      storage: 10Gi
  selector:
    # To make sure we match the claim with the exact volume, match the label
    matchLabels:
      usage: ref1-mongo-pv