apiVersion: v1
kind: Secret
metadata:
  name: ref1-azure-mongo-secret
  namespace: qualdo
data:
  # You can include additional key value pairs
  azurestorageaccountname: cXVhbGRvZGV2bW9uZ28xCg==
  azurestorageaccountkey: OU1jM1dZMmdrZUYwTzkvY0VWNXNNZ3dQR1ZwNmxLTFZ2ckxZVm9ocDZiWXBJK2pTRWVmUzVLMUdEL0RaV0VwNjZjckwxNkk2TEkxdCtBU3RvdjFzN3c9PQo=