apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: qualdo
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: mongo-check-nandha
spec:
  type: LoadBalancer
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: qualdo
spec:
  selector:
    matchLabels:
      app: mongo
  serviceName: "mongo"
  replicas: 3
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          command:
            - mongod
            - "--bind_ip_all"
            - "--replSet"
            - rs0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: ref1-azure-vol
              mountPath: /data/db
      volumes:
        - name: ref1-azure-vol
          persistentVolumeClaim:
            claimName: ref1-mongo-pvc